import{a as q,S as P,i}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const S="49758339-0242343cad2ae6f5246dcc16e",E="https://pixabay.com/api/",B=15;async function f(n,r){const o={key:S,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:B};return(await q.get(E,{params:o})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new P(".gallery a",{captionsData:"alt",captionDelay:250});function p(n){const r=n.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:a,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img src="${o}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${a}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${v}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){m.innerHTML=""}function g(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function A(){y.classList.remove("hidden")}function b(){y.classList.add("hidden")}const u=document.querySelector(".form"),I=document.querySelector(".gallery"),O=document.querySelector(".load-more");document.querySelector(".loader");let c=1,l="",d=0;u.addEventListener("submit",async n=>{n.preventDefault();const r=u.elements["search-text"].value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search query."});return}l=r,c=1,$(),b(),g();try{const o=await f(l,c);if(d=o.totalHits,o.hits.length===0){i.info({title:"Info",message:"No images found. Please try a different query."});return}p(o.hits),d>15&&A()}catch{i.error({title:"Error",message:"An error occurred while fetching images."})}finally{L()}});O.addEventListener("click",async()=>{c+=1,g();try{const n=await f(l,c);p(n.hits);const r=Math.ceil(d/15);c>=r&&(b(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const{height:o}=I.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}catch{i.error({title:"Error",message:"An error occurred while fetching images."})}finally{L()}});
//# sourceMappingURL=index.js.map
